name: easy_journey
description: "Your project description"
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0 
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1

# ... other configurations
flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/second.png
    - assets/welcome.png
    - assets/background.png
    - assets/destination.jpg
    - assets/payment.jpg
    - assets/success.png
    - assets/list.jpg
    - assets/seat.png
dev_dependencies:
  get: ^4.6.6
