name: easy_journey
description: "Your project description"
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.3+2
  google_sign_in: ^5.2.1
  firebase_core: ^1.10.0

  # ... other dependencies

# ... other configurations

flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/second.png
    - assets/welcome.png
    - assets/background.png
    - assets/destination.jpg
    - assets/list.jpg
    - assets/seat.png
    - assets/payment.jpg
    - assets/success.png
    
